INSERT INTO `zone_category` (`parent_zone_category_id`, `zone_category_name`)
VALUES (NULL, '서울'),
       (NULL, '광주'),
       (NULL, '인천'),
       (NULL, '대전'),
       (NULL, '대구'),
       (NULL, '전남'),
       (NULL, '경북'),
       (NULL, '경남'),
       (NULL, '부산'),
       (NULL, '울산'),
       (NULL, '제주'),
       (NULL, '경기'),
       (NULL, '강원'),
       (NULL, '충북'),
       (NULL, '충남'),
       (NULL, '전북');

INSERT INTO `zone_category` (`parent_zone_category_id`, `zone_category_name`)
VALUES (1, '강남구'),
       (1, '강동구'),
       (1, '강북구'),
       (1, '강서구'),
       (1, '관악구'),
       (1, '광진구'),
       (1, '구로구'),
       (1, '금천구'),
       (1, '노원구'),
       (1, '도봉구'),
       (1, '동대문구'),
       (1, '동작구'),
       (1, '마포구'),
       (1, '서대문구'),
       (1, '서초구'),
       (1, '성동구'),
       (1, '성북구'),
       (1, '송파구'),
       (1, '양천구'),
       (1, '영등포구'),
       (1, '용산구'),
       (1, '은평구'),
       (1, '종로구'),
       (1, '중구'),
       (1, '중랑구');

INSERT INTO `zone_category` (`parent_zone_category_id`, `zone_category_name`)
VALUES (2, '동구'),
       (2, '서구'),
       (2, '남구'),
       (2, '북구'),
       (2, '광산구');

INSERT INTO `zone_category` (`parent_zone_category_id`, `zone_category_name`)
VALUES (3, '중구'),
       (3, '동구'),
       (3, '미추홀구'),
       (3, '연수구'),
       (3, '남동구'),
       (3, '부평구'),
       (3, '계양구'),
       (3, '서구'),
       (3, '강화군'),
       (3, '옹진군');

INSERT INTO `zone_category` (`parent_zone_category_id`, `zone_category_name`)
VALUES (4, '동구'),
       (4, '중구'),
       (4, '서구'),
       (4, '유성구'),
       (4, '대덕구');

INSERT INTO `zone_category` (`parent_zone_category_id`, `zone_category_name`)
VALUES (5, '중구'),
       (5, '동구'),
       (5, '서구'),
       (5, '남구'),
       (5, '북구'),
       (5, '수성구'),
       (5, '달서구'),
       (5, '달성군'),
       (5, '군위군');

INSERT INTO `zone_category` (`parent_zone_category_id`, `zone_category_name`)
VALUES (6, '목포시'),
       (6, '여수시'),
       (6, '순천시'),
       (6, '나주시'),
       (6, '광양시'),
       (6, '담양군'),
       (6, '곡성군'),
       (6, '구례군'),
       (6, '고흥군'),
       (6, '보성군'),
       (6, '화순군'),
       (6, '장흥군'),
       (6, '강진군'),
       (6, '해남군'),
       (6, '영암군'),
       (6, '무안군'),
       (6, '함평군'),
       (6, '영광군'),
       (6, '장성군'),
       (6, '완도군'),
       (6, '진도군'),
       (6, '신안군');

INSERT INTO `zone_category` (`parent_zone_category_id`, `zone_category_name`)
VALUES (7, '포항시'),
       (7, '경주시'),
       (7, '김천시'),
       (7, '안동시'),
       (7, '구미시'),
       (7, '영주시'),
       (7, '영천시'),
       (7, '상주시'),
       (7, '문경시'),
       (7, '경산시'),
       (7, '의성군'),
       (7, '청송군'),
       (7, '영양군'),
       (7, '영덕군'),
       (7, '청도군'),
       (7, '고령군'),
       (7, '성주군'),
       (7, '칠곡군'),
       (7, '예천군'),
       (7, '봉화군'),
       (7, '울진군'),
       (7, '울릉군');

INSERT INTO `zone_category` (`parent_zone_category_id`, `zone_category_name`)
VALUES (8, '창원시'),
       (8, '김해시'),
       (8, '진주시'),
       (8, '양산시'),
       (8, '거제시'),
       (8, '통영시'),
       (8, '사천시'),
       (8, '밀양시'),
       (8, '함안군'),
       (8, '거창군'),
       (8, '창녕군'),
       (8, '고성군'),
       (8, '하동군'),
       (8, '합천군'),
       (8, '남해군'),
       (8, '함양군'),
       (8, '산청군'),
       (8, '의령군');

INSERT INTO `zone_category` (`parent_zone_category_id`, `zone_category_name`)
VALUES (9, '중구'),
       (9, '서구'),
       (9, '동구'),
       (9, '영도구'),
       (9, '부산진구'),
       (9, '동래구'),
       (9, '남구'),
       (9, '북구'),
       (9, '해운대구'),
       (9, '사하구'),
       (9, '금정구'),
       (9, '강서구'),
       (9, '연제구'),
       (9, '수영구'),
       (9, '사상구'),
       (9, '기장군');

INSERT INTO `zone_category` (`parent_zone_category_id`, `zone_category_name`)
VALUES (10, '중구'),
       (10, '남구'),
       (10, '동구'),
       (10, '북구'),
       (10, '울주군');

INSERT INTO `zone_category` (`parent_zone_category_id`, `zone_category_name`)
VALUES (11, '서귀포시'),
       (11, '제주시');

INSERT INTO `zone_category` (`parent_zone_category_id`, `zone_category_name`)
VALUES (12, '수원시'),
       (12, '성남시'),
       (12, '용인시'),
       (12, '안양시'),
       (12, '안산시'),
       (12, '과천시'),
       (12, '광명시'),
       (12, '광주시'),
       (12, '군포시'),
       (12, '부천시'),
       (12, '시흥시'),
       (12, '김포시'),
       (12, '안성시'),
       (12, '오산시'),
       (12, '의왕시'),
       (12, '이천시'),
       (12, '평택시'),
       (12, '하남시'),
       (12, '화성시'),
       (12, '여주시'),
       (12, '양평군'),
       (12, '고양시'),
       (12, '구리시'),
       (12, '남양주시'),
       (12, '동두천시'),
       (12, '양주시'),
       (12, '의정부시'),
       (12, '파주시'),
       (12, '포천시'),
       (12, '연천군'),
       (12, '가평군');

INSERT INTO `zone_category` (`parent_zone_category_id`, `zone_category_name`)
VALUES (13, '원주시'),
       (13, '춘천시'),
       (13, '강릉시'),
       (13, '동해시'),
       (13, '속초시'),
       (13, '삼척시'),
       (13, '태백시'),
       (13, '홍천군'),
       (13, '철원군'),
       (13, '횡성군'),
       (13, '평창군'),
       (13, '정선군'),
       (13, '영월군'),
       (13, '인제군'),
       (13, '고성군'),
       (13, '양양군'),
       (13, '화천군'),
       (13, '양구군');

INSERT INTO `zone_category` (`parent_zone_category_id`, `zone_category_name`)
VALUES (14, '청주시'),
       (14, '충주시'),
       (14, '제천시'),
       (14, '보은군'),
       (14, '옥천군'),
       (14, '영동군'),
       (14, '증평군'),
       (14, '진천군'),
       (14, '괴산군'),
       (14, '음성군'),
       (14, '단양군');

INSERT INTO `zone_category` (`parent_zone_category_id`, `zone_category_name`)
VALUES (15, '천안시'),
       (15, '공주시'),
       (15, '보령시'),
       (15, '아산시'),
       (15, '서산시'),
       (15, '논산시'),
       (15, '계룡시'),
       (15, '당진시'),
       (15, '금산군'),
       (15, '부여군'),
       (15, '서천군'),
       (15, '청양군'),
       (15, '홍성군'),
       (15, '예산군'),
       (15, '태안군');

INSERT INTO `zone_category` (`parent_zone_category_id`, `zone_category_name`)
VALUES (16, '전주시'),
       (16, '익산시'),
       (16, '군산시'),
       (16, '정읍시'),
       (16, '김제시'),
       (16, '남원시'),
       (16, '완주군'),
       (16, '고창군'),
       (16, '부안군'),
       (16, '임실군'),
       (16, '순창군'),
       (16, '진안군'),
       (16, '무주군'),
       (16, '장수군');

INSERT INTO `zone_category` (`parent_zone_category_id`, `zone_category_name`) VALUES (NULL, '세종');
INSERT INTO `zone_category` (`parent_zone_category_id`, `zone_category_name`) VALUES (245, '세종');

